export const LOGIN = '/login'
export const FORGOTPASSWORD = '/forgot-password'
export const DASHBOARD = '/dashboard'
export const LEADLIST = '/leadList'
export const COMPANIES = '/companies'
export const ROLES = '/roles'
export const PAGES = '/pages'
export const USERS = '/users'
export const NEWROLE = '/new-role'
export const NEWPAGE = '/new-page'
export const PROFILE = '/profile'
export const SUPPORT = '/support'
export const TICKETDETAIL = '/ticket-detail'
export const COMPANY = '/company'

export const INDUSTRYTYPES = '/master/industry-types'